### ISSUE TITLE
Guitar Pedal distro

### ISSUE THREAD

**Issue by colinbrogan** [guysoft/CustomPiOS#40]
This is not really an issue or bug, there just isn't a good way to dm on github. I've been following your posts on Audio Injector. I have independently built a realtime version of Raspian Stretch, with intention to share as a kind of distro, or prepackaged image for people who want to jump quick into building guitar pedals. It would have the following additional features:

- Auto Wifi Hotspot for easy wireless ssh out of the box
- Seriously gutted systemd for rapid boot-time
- Jack and other audio program boot scripts, with low-latency settings already in place for the main cards (Audio Injector, etc)

I am wondering if, instead of maintaining this seperately by different tools, I should merge this effort with your project. I have not used CustomPiOS, but I can look into it if you feel that there is any benefit to combining effort.

**Comment by colinbrogan** [comment]
This is a current project that I am doing:
[http://essej.net/slforum/viewtopic.php?f=21&t=4972](url)
There is just too much setup work I've had to go through to start building viable pedals with the RPi. I plan to build more, so it seems more than worth it to me to try and share that setup work, and build a platform for fellow custom pedal programmers.

**Comment by guysoft** [comment]
Hey, so first its good you posted here and not privately.

First you might like to look both [RealtimePi](https://github.com/guysoft/RealtimePi) which is a distro I maintain that has a realtime kenrel (It takes a long time to build, be warned).
And I am also helping [Zynthian project](http://zynthian.org/) build [ZynthianOS](https://github.com/guysoft/ZynthianOS).
Those distros combined both have a realtime kernel and scripts to install and configure jack.

Inline reply: 
>    Auto Wifi Hotspot for easy wireless ssh out of the box

Use the [auto-hotspot module](https://github.com/guysoft/CustomPiOS/wiki/Modules#auto-hotspot)
> Seriously gutted systemd for rapid boot-time

Raspbian LIte is pretty guttered, you can write scripts to remove more stuff. Stick to Raspbian because they also have non-free stuff there which you need.

>    Jack and other audio program boot scripts, with low-latency settings already in place for the main cards (Audio Injector, etc)

Look at how Zynthian do it.


I would recommend you build a CustomPiOS distro and base it of the baseimage of RealtimePi, to save the hours of compilation. It would let you focus on what you want and release something working in a short time.

**Comment by guysoft** [comment]
Is there any progress with this? Can I close the issue?

**Comment by guysoft** [comment]
Does it use RealtimePi or CustomPiOS?

**Comment by colinbrogan** [comment]
So, I actually compiled my own realtime kernel on top of Raspbian, and it works. However, at some point I want to optimize a rapid boot time (currently boots at 1:30), and share it as it's own distro. I guess the question is whether or not I should join efforts with what your doing, or keep going on my own path.

**Comment by colinbrogan** [comment]
NP, sorry to derail your issue channel.

**Comment by guysoft** [comment]
No problem,  might help others

**Comment by guysoft** [comment]
Nothing to act upon, closing
