### ISSUE TITLE
gitclone call question

### ISSUE THREAD

**Issue by cwalton** [guysoft/CustomPiOS#61]
https://github.com/guysoft/CustomPiOS/blob/e9d972eeddaf1b7c1d642e73a4f97c5ec2e6143b/src/common.sh#L65

I can’t find any other reference to “${REPO}”. Is this a bug?  Should it be $1 instead of "${REPO}"

**Comment by guysoft** [comment]
Indeed, looks like it came in from commit:
https://github.com/guysoft/CustomPiOS/commit/881d4165b2f85d62f863534420f93d80eccd397c

That bit of code deals if you are cloning repo that ends with ``.git``.  Which does not happen anymore in all the distros I maintain since I specify the folder name in advance.

Will be fixed.

cc @foosel who made that commit :smiley:
